CVSRCS_ID           := "$$Name: AstroH_B01 $$ $$Id: Makefile,v 1.3 2012/06/28 16:21:58 dhon Exp $$"

$(info $$Name: AstroH_B01 $$ $$Id: Makefile,v 1.3 2012/06/28 16:21:58 dhon Exp $$)

HD_COMPONENT_NAME		= astroh

HD_COMPONENT_VERS		= 

HD_SUBDIRS			    = ahtlm ahhxi ahsgd

HD_TEST_SUBDIRS			= ${HD_SUBDIRS}

include ${HD_STD_MAKEFILE}
