CVSRCS_ID           := "$$Name: AstroH_B01 $$ $$Id: Makefile,v 1.3 2012/06/28 16:21:59 dhon Exp $$"

$(info $$Name: AstroH_B01 $$ $$Id: Makefile,v 1.3 2012/06/28 16:21:59 dhon Exp $$)

HD_COMPONENT_NAME		= astroh

HD_COMPONENT_VERS		= 

HD_SUBDIRS			    = ahtlm src

HD_TEST_SUBDIRS			= src/test

include ${HD_STD_MAKEFILE}
