CVSRCS_ID           := "$$Name: AstroH_B01 $$ $$Id: Makefile,v 1.4 2012/06/28 14:14:55 dhon Exp $$"

$(info $$Name: AstroH_B01 $$ $$Id: Makefile,v 1.4 2012/06/28 14:14:55 dhon Exp $$)

HD_COMPONENT_NAME   = astroh

HD_COMPONENT_VERS   = 

HD_SUBDIRS          = lib tasks 

HD_TEST_SUBDIRS     = lib

include ${HD_STD_MAKEFILE}
