CVSRCS_ID           := "$$Name: AstroH_B01 $$ $$Id: Makefile,v 1.3 2012/06/29 15:30:11 peachey Exp $$"

$(info $$Name: AstroH_B01 $$ $$Id: Makefile,v 1.3 2012/06/29 15:30:11 peachey Exp $$)

HD_COMPONENT_NAME	= astroh

HD_COMPONENT_VERS	=

HD_INC_SUBDIR		= ahhxi

HD_INSTALL_HEADERS	= ahHXItyps.h

include ${HD_STD_MAKEFILE}
