HD_COMPONENT_NAME	= astroh

HD_COMPONENT_VERS	= 

HD_TEST_CXXTASK		= testahtime

HD_TEST_CXXTASK_SRC_cxx	= ${HD_TEST_CXXTASK}.cxx

HD_CXXFLAGS		= ${HD_STD_CXXFLAGS}

HD_CXXLIBS		= ${HD_LFLAGS} -lahtime -lahlog -lst_stream -lahfits -lahmath -lahgen ${HD_STD_LIBS} ${SYSLIBS}

HD_TEST_TASKS		= ${HD_TEST_CXXTASK}

include ${HD_STD_MAKEFILE}
