HD_COMPONENT_NAME	= astroh

HD_COMPONENT_VERS	= 

HD_INC_SUBDIR		= ahtime

HD_INSTALL_HEADERS	= ahtime.h ahcolumndef.h ahdelay.h ahtimeassign.h ahtimfile.h AhTimeUTC.h AhTimeTT.h AhTimeTAI.h ahleapsec.h ahtimeconv.h

include ${HD_STD_MAKEFILE}
