HD_COMPONENT_NAME	= astroh

HD_COMPONENT_VERS	= 

HD_LIBRARY_ROOT		= ahtime

HD_LIBRARY_SRC_cxx	= ahtime.cxx ahcolumndef.cxx ahdelay.cxx ahtimeassign.cxx ahtimfile.cxx AhTimeUTC.cxx AhTimeTT.cxx AhTimeTAI.cxx ahleapsec.cxx ahtimeconv.cxx

HD_CXXFLAGS		= ${HD_STD_CXXFLAGS}

HD_INSTALL_LIBRARIES	= ${HD_LIBRARY_ROOT}

include ${HD_STD_MAKEFILE}
